/**
 * Define interfaces for table rows (optional but recommended for type safety)
 * Ensure these match your actual DB ENUM types
 */

export interface VideosRow {
  video_id: string;
  title: string | null;
  channel_id: string | null;
  channel_title: string | null;
  first_fetched_at: string | null;
  last_fetched_at: string | null;
}

export interface Database {
  videos: VideosRow;
  comments: CommentsRow;
  comment_updates: CommentUpdatesRow;
  crawl_status: CrawlStatusRow;
}

// Ensure these match your actual DB ENUM types
export enum CrawlSortBy {
  POPULAR = "POPULAR",
  RECENT = "RECENT",
}

export interface YoutubeYtcfg {
  INNERTUBE_CONTEXT: Record<string, unknown>;
  INNERTUBE_API_KEY: string;
  [key: string]: unknown;
}

/* CrawlStatusEnum removed: status is no longer orchestrated in DB */

export interface CrawlStatusRow {
  crawl_id: number;
  video_id: string;
  sort_by: CrawlSortBy;
  continuation_token: string | null;
  last_attempted_at: string | null;
  last_successful_page_at: string | null;
  error_message: string | null;
  created_at: string;
  updated_at: string;
  ytcfg: YoutubeYtcfg | null;
}

export interface CommentsRow {
  comment_id: string;
  video_id: string;
  parent_comment_id: string | null;
  text: string;
  published_at: string | null; // Supabase returns dates as strings
  author_display_name: string | null;
  author_channel_id: string | null;
  author_photo_url: string | null;
  votes: number | null;
  reply_count: number | null;
  is_hearted: boolean | null;
  is_paid: boolean | null;
  raw_time_string: string | null;
  first_seen_at: string | null; // Supabase returns dates as strings
  last_updated_at: string | null; // Supabase returns dates as strings
}

export interface CommentUpdatesRow {
  update_id?: number; // Optional as it's generated by DB
  comment_id: string;
  attribute_name: string;
  old_value: string | null;
  new_value: string | null;
  updated_at?: string; // Optional as it's generated by DB
}

export interface Env {
  // Proxy configuration environment variables
  PROXY_URL?: string;
  PROXY_USERNAME?: string;
  PROXY_PASSWORD?: string;
  PROXY_CONFIG?: string;  // JSON configuration for multiple proxies
  
  // Other environment variables
  [key: string]: string | undefined;
}
