name: Build Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'worker/**'
      - '.github/workflows/check.yml'
      - '.github/workflows/deploy.yml'

jobs:
  ai:
    runs-on: ubuntu-latest
    name: Lint and Build Check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
      
      - name: Run lint
        run: bun run lint

      - name: Run build
        run: bun run build
