name: Deploy Server to Cloudflare Worker

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Trigger deployment only on pushes to the main branch
    paths:
      - 'frontend/**'
      - 'worker/**'
      - '.github/workflows/deploy.yml' # Or if the workflow file itself changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write # Required for cloudflare/pages-action
    name: Deploy Server to Cloudflare Worker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Running bun install
        run: |
          bun install
      
      - name: Deploy
        run: |
          bun run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
          VITE_POSTHOG_KEY: ${{ secrets.VITE_POSTHOG_KEY }}
          VITE_POSTHOG_HOST: ${{ secrets.VITE_POSTHOG_HOST }}
